# Generated by Django 3.1.4 on 2020-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20201218_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='date',
            field=models.DateField(blank=True, default='2020-10-01'),
            preserve_default=False,
        ),
    ]
