# Generated by Django 3.1.4 on 2020-12-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_month_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ledger.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repayment',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ledger.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savings',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ledger.person'),
            preserve_default=False,
        ),
    ]
